In [3]:
import pandas as pd
import sqlite3

In [7]:
connection = sqlite3.connect(
    "customer360.db"
)

In [8]:
import os

os.chdir(
    r"C:\Users\shree\Downloads\Customer 360 Intelligence Platform – E-Commerce Analytics"
)

os.getcwd()

'C:\\Users\\shree\\Downloads\\Customer 360 Intelligence Platform – E-Commerce Analytics'

In [10]:
customer_360 = pd.read_csv(
    "Data/customer_360_master.csv"
)

segments = pd.read_csv(
    "Data/customer_segments.csv"
)

sentiment = pd.read_csv(
    "Data/customer_sentiment.csv"
)

In [12]:
print(customer_360.shape)
print(segments.shape)
print(sentiment.shape)

(110173, 22)
(93336, 6)
(40977, 8)

In [14]:
os.getcwd()

'C:\\Users\\shree\\Downloads\\Customer 360 Intelligence Platform – E-Commerce Analytics'

In [16]:
customer_360.to_sql(
    "customer360",
    connection,
    if_exists="replace",
    index=False
)

segments.to_sql(
    "customer_segments",
    connection,
    if_exists="replace",
    index=False
)

sentiment.to_sql(
    "customer_sentiment",
    connection,
    if_exists="replace",
    index=False
)

40977

In [17]:
query = """

SELECT name
FROM sqlite_master
WHERE type='table'

"""


pd.read_sql(
    query,
    connection
)

                 name
0         customer360
1   customer_segments
2  customer_sentiment

In [19]:
query = """

SELECT *
FROM customer360
LIMIT 5

"""


pd.read_sql(
    query,
    connection
)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,delivery_days,purchase_month,...,customer_zip_code_prefix,customer_city,customer_state,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,total_revenue
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,8,10,...,3149,sao paulo,SP,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,38.71
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,13,7,...,47813,barreiras,BA,1,595fac2a385ac33a80bd5114aec74eb8,289cdb325fb7e7f891c38608bf9e0962,2018-07-30 03:24:27,118.70,22.76,141.46
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,9,8,...,75265,vianopolis,GO,1,aa4383b373c6aca5d8797843e5594415,4869f7a5dfa277a7dca6462dcf3b52b2,2018-08-13 08:55:23,159.90,19.22,179.12
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,13,11,...,59296,sao goncalo do amarante,RN,1,d0b61bfb1de832b15ba9d266ca96e5b0,66922902710d126a0e7d26b0e3805106,2017-11-23 19:45:59,45.00,27.20,72.20
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,2,2,...,9195,santo andre,SP,1,65266b2da20d04dbe00c5c2d3bb7859e,2c9e548be18521d1c43cde1c582c6de8,2018-02-19 20:31:37,19.90,8.72,28.62

In [21]:
query = """

SELECT 
    ROUND(SUM(total_revenue),2) AS Total_Revenue
FROM customer360;

"""


pd.read_sql(
    query,
    connection
)

   Total_Revenue
0    15416246.25

In [23]:
query = """

SELECT
    purchase_year,
    purchase_month,
    ROUND(SUM(total_revenue),2) AS Revenue

FROM customer360

GROUP BY 
    purchase_year,
    purchase_month

ORDER BY 
    purchase_year,
    purchase_month;

"""


pd.read_sql(
    query,
    connection
)

    purchase_year  purchase_month     Revenue
0            2016               9      143.46
1            2016              10    46490.66
2            2016              12       19.62
3            2017               1   127367.44
4            2017               2   269399.65
5            2017               3   414330.95
6            2017               4   390812.40
7            2017               5   566657.40
8            2017               6   490050.37
9            2017               7   566299.08
10           2017               8   645832.36
11           2017               9   700883.51
12           2017              10   751117.01
13           2017              11  1153229.37
14           2017              12   843078.29
15           2018               1  1077887.46
16           2018               2   966168.41
17           2018               3  1120598.24
18           2018               4  1132878.93
19           2018               5  1128774.52
20           2018               6  1011448.96
21           2018               7  1027286.52
22           2018               8   985491.64

In [25]:
query = """

SELECT
    customer_unique_id,
    ROUND(SUM(total_revenue),2) AS Customer_Value

FROM customer360

GROUP BY customer_unique_id

ORDER BY Customer_Value DESC

LIMIT 10;

"""


pd.read_sql(
    query,
    connection
)

                 customer_unique_id  Customer_Value
0  0a0a92112bd4c708ca5fde585afaa872        13664.08
1  da122df9eeddfedc1dc1f5349a1a690c         7571.63
2  763c8b1c9c68a0229c42c9fc6f662b93         7274.88
3  dc4802a71eae9be1dd28f5d788ceb526         6929.31
4  459bef486812aa25204be022145caa62         6922.21
5  ff4159b92c40ebe40454e3e6a7c35ed6         6726.66
6  4007669dec559734d6f53e029e360987         6081.54
7  eebb5dda148d3893cdaf5b5ca3040ccb         4764.34
8  48e1ac109decbb87765a3eade6854098         4681.78
9  c8460e4251689ba205045f3ea17884a1         4655.88

In [27]:
query = """

SELECT

    s.Customer_Segment,

    COUNT(
        DISTINCT c.customer_unique_id
    ) AS Total_Customers,


    ROUND(
        SUM(c.total_revenue),
        2
    ) AS Revenue


FROM customer360 c


JOIN customer_segments s

ON c.customer_unique_id =
   s.customer_unique_id


GROUP BY
    s.Customer_Segment


ORDER BY
    Revenue DESC;


"""


pd.read_sql(
    query,
    connection
)

   Customer_Segment  Total_Customers     Revenue
0  Regular Customer            52102  8309889.68
1  At Risk Customer            38428  6194869.96
2  Premium Customer             2806   911486.61

In [29]:
query = """

SELECT

customer_unique_id,

Total_Revenue,


RANK()
OVER(
ORDER BY Total_Revenue DESC
)
AS Customer_Rank


FROM
(

SELECT

customer_unique_id,

ROUND(
SUM(total_revenue),
2
)
AS Total_Revenue


FROM customer360


GROUP BY customer_unique_id

)


LIMIT 10;


"""


pd.read_sql(
    query,
    connection
)

                 customer_unique_id  Total_Revenue  Customer_Rank
0  0a0a92112bd4c708ca5fde585afaa872       13664.08              1
1  da122df9eeddfedc1dc1f5349a1a690c        7571.63              2
2  763c8b1c9c68a0229c42c9fc6f662b93        7274.88              3
3  dc4802a71eae9be1dd28f5d788ceb526        6929.31              4
4  459bef486812aa25204be022145caa62        6922.21              5
5  ff4159b92c40ebe40454e3e6a7c35ed6        6726.66              6
6  4007669dec559734d6f53e029e360987        6081.54              7
7  eebb5dda148d3893cdaf5b5ca3040ccb        4764.34              8
8  48e1ac109decbb87765a3eade6854098        4681.78              9
9  c8460e4251689ba205045f3ea17884a1        4655.88             10

In [35]:
query = """

WITH CustomerRevenue AS
(

SELECT

customer_unique_id,

SUM(total_revenue)
AS Revenue

FROM customer360

GROUP BY customer_unique_id

)


SELECT *

FROM CustomerRevenue


WHERE Revenue >
(
SELECT AVG(Revenue)
FROM CustomerRevenue
)


ORDER BY Revenue DESC;


"""


pd.read_sql(
    query, 
    connection
).head(10)

                 customer_unique_id   Revenue
0  0a0a92112bd4c708ca5fde585afaa872  13664.08
1  da122df9eeddfedc1dc1f5349a1a690c   7571.63
2  763c8b1c9c68a0229c42c9fc6f662b93   7274.88
3  dc4802a71eae9be1dd28f5d788ceb526   6929.31
4  459bef486812aa25204be022145caa62   6922.21
5  ff4159b92c40ebe40454e3e6a7c35ed6   6726.66
6  4007669dec559734d6f53e029e360987   6081.54
7  eebb5dda148d3893cdaf5b5ca3040ccb   4764.34
8  48e1ac109decbb87765a3eade6854098   4681.78
9  c8460e4251689ba205045f3ea17884a1   4655.88

In [36]:
query = """

PRAGMA table_info(customer360);

"""

pd.read_sql(
    query,
    connection
)

    cid                           name     type  notnull dflt_value  pk
0     0                       order_id     TEXT        0       None   0
1     1                    customer_id     TEXT        0       None   0
2     2                   order_status     TEXT        0       None   0
3     3       order_purchase_timestamp     TEXT        0       None   0
4     4              order_approved_at     TEXT        0       None   0
5     5   order_delivered_carrier_date     TEXT        0       None   0
6     6  order_delivered_customer_date     TEXT        0       None   0
7     7  order_estimated_delivery_date     TEXT        0       None   0
8     8                  delivery_days  INTEGER        0       None   0
9     9                 purchase_month  INTEGER        0       None   0
10   10                  purchase_year  INTEGER        0       None   0
11   11             customer_unique_id     TEXT        0       None   0
12   12       customer_zip_code_prefix  INTEGER        0       None   0
13   13                  customer_city     TEXT        0       None   0
14   14                 customer_state     TEXT        0       None   0
15   15                  order_item_id  INTEGER        0       None   0
16   16                     product_id     TEXT        0       None   0
17   17                      seller_id     TEXT        0       None   0
18   18            shipping_limit_date     TEXT        0       None   0
19   19                          price     REAL        0       None   0
20   20                  freight_value     REAL        0       None   0
21   21                  total_revenue     REAL        0       None   0

In [39]:
query = """

SELECT

product_id,

ROUND(
SUM(total_revenue),
2
)
AS Revenue,

COUNT(order_id)
AS Total_Orders


FROM customer360


GROUP BY
product_id


ORDER BY
Revenue DESC


LIMIT 10;


"""


pd.read_sql(
    query,
    connection
)

                         product_id   Revenue  Total_Orders
0  bb50f2e236e5eea0100680137654686c  67258.03           194
1  d1c427060a0f73f6b889a5c7c61f2ac4  58957.31           332
2  6cdd53843498f92890544667809f1595  57933.73           153
3  99a4788cb24856965c36a24e339b6058  49907.50           477
4  3dd2a17168ec895c781a9191c1e95ad7  47876.06           272
5  d6160fb7873f184099d9bc95e30376af  47314.18            33
6  aca2eb7d00ea1a7b8ebd4e68314663af  44197.75           520
7  5f504b3a1c75b73d6151be81eb05bdc9  41725.81            63
8  25c38557cf793876c5abdd5931f922db  40311.95            38
9  53b36df67ebb7c41585e8d54d6772e08  39713.49           321